# Generated by Django 4.2.1 on 2023-05-25 07:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='myApp.userprofile')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='myApp.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255, unique=True)),
                ('debts', models.ManyToManyField(null=True, to='myApp.debt')),
                ('members', models.ManyToManyField(to='myApp.userprofile')),
            ],
        ),
    ]
