# Generated by Django 4.2.1 on 2023-05-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_remove_group_debts_remove_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='debts',
            field=models.ManyToManyField(null=True, to='myApp.debt'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='myApp.userprofile'),
        ),
    ]
