# Generated by Django 4.2.1 on 2023-05-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_remove_group_debts'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='debts',
            field=models.ManyToManyField(null=True, to='myApp.debt'),
        ),
    ]
