# Generated by Django 4.2.1 on 2023-05-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_group_debts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='ExpenseGroup',
        ),
    ]
