# Generated by Django 4.2.1 on 2023-05-27 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_rename_group_expensegroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseGroup',
            new_name='Group',
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paidBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_by', to='myApp.userprofile')),
                ('selectedGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_group', to='myApp.group')),
                ('splitbtw', models.ManyToManyField(to='myApp.userprofile')),
            ],
        ),
    ]
