# Generated by Django 4.2.1 on 2023-06-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_rename_expensegroup_group_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
