# Generated by Django 4.2.1 on 2023-07-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_rename_id_group_id_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='debts',
            field=models.ManyToManyField(blank=True, to='myApp.debt'),
        ),
    ]
